site_name: RL Insights
site_author: Florian LAURENT
site_description: A reinforcement learning knowledge base
copyright: 'Copyright &copy; 2020 Florian Laurent'

repo_url: https://github.com/MasterScrat/rl-insights
edit_uri: ""

nav:
  - Home: index.md
  - Papers:
      - curl.md
      - a3c.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'orange'

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true

extra_css:
  - 'stylesheets/extra.css'

google_analytics:
  - UA-36471625-6
  - auto