site_name: RL Insights
site_author: Florian LAURENT
site_description: A reinforcement learning knowledge base
copyright: 'Copyright &copy; 2020 Florian Laurent'

repo_url: https://github.com/MasterScrat/rl-insights
edit_uri: ""

nav:
  - Home: index.md
  - Papers:
      - curl.md
      - a3c.md
  - Notebooks:
      - 'Test notebook 1': notebooks/RL_Research_Workflow.ipynb
      - 'Test notebook 2': notebooks/Title_of_the_notebook.ipynb
  - Blog:
      - notebook-pitfalls.md
      - notebooks-long-tasks.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'orange'

plugins:
  - search
  - git-revision-date-localized
  - mknotebooks:
      enable_default_jupyter_cell_styling: true
      enable_default_pandas_dataframe_styling: true
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: false
  - pymdownx.arithmatex
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - 'js/extra.js'

google_analytics:
  - UA-36471625-6
  - auto