site_name: RL Insights
repo_url: https://github.com/MasterScrat/rl-insights
site_author: Florian LAURENT
site_description: Reinforcement learning resources
copyright: 'Copyright &copy; 2020 Florian Laurent'

nav:
  - Home: index.md
  - Papers:
      - curl.md
      - a3c.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'orange'

markdown_extensions:
  - admonition
  - footnotes

extra_css:
  - 'stylesheets/extra.css'

google_analytics:
  - UA-36471625-6
  - auto