site_name: RL Insights
repo_url: https://github.com/MasterScrat/rl-insights
repo_name: MasterScrat/rl-insights
edit_uri: edit/master/docs
site_author: Florian LAURENT
site_description: Reinforcement learning resources

nav:
  - Home: index.md
  - Papers:
      - curl.md
      - a3c.md
      - acer.md
      - ppo.md
      - rainbow.md
  - Concepts:
      - policy-based-methods.md
      - policy-gradient-methods.md
      - value-based-methods.md
      - actor-critic.md
      - cem.md
      - distributed-training.md
      - experience-replay.md
      - gae.md
      - rl-approaches.md
      - sample-efficiency.md
  - FAQ:
      - what-is-rl.md
      - why-dnq-not-converging.md
      - methods-comparison.md
      - tips-and-tricks.md
      - best-resources.md
      - foundational-papers.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'orange'

markdown_extensions:
  - admonition
  - footnotes

extra_css:
  - 'stylesheets/extra.css'

copyright: 'Copyright &copy; 2020 Florian Laurent'